'use client';
import { useEffect, useState } from 'react';
import { Check, Moon, Sun } from 'lucide-react';
import { workbenchRpc } from '../services';
export interface UiPreferences {name:string;theme:'light'|'dark';dailyMinutes:number;revision:number}
export default function PreferencesEditor({initial,onSaved,onClose=()=>{},page='prefs'}:{initial:UiPreferences;onSaved:()=>Promise<void>;onClose?:()=>void;page?:'prefs'|'display'|'profile'}) {
  const [draft,setDraft]=useState(initial),[baseline,setBaseline]=useState(initial),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const same=(a:UiPreferences,b:UiPreferences)=>a.name===b.name&&a.theme===b.theme&&a.dailyMinutes===b.dailyMinutes;
  useEffect(()=>{if(initial.revision>baseline.revision&&same(draft,baseline)&&!busy){setDraft(initial);setBaseline(initial);}},[initial,draft,baseline,busy]);
  return <form className="settings-page integrated-preferences" onSubmit={async event=>{event.preventDefault();const submitted=draft;setBusy(true);setError('');try{const saved=await workbenchRpc<UiPreferences>('uiPreferences',{...submitted,baseVersion:submitted.revision});setBaseline(saved);setDraft(current=>same(current,submitted)?saved:{...current,revision:saved.revision});await onSaved();}catch(error){setError(error instanceof Error?error.message:'无法保存偏好');}finally{setBusy(false);}}}>
    <div className="settings-page-scroll" key={page}><header className="settings-page-heading"><span className="eyebrow">你的使用习惯</span><h3>{page==='display'?'显示与交互':page==='profile'?'用户资料':'用户偏好'}</h3>{page!=='display'&&<p>调整称呼和学习目标，按自己的节奏前进。</p>}</header>
    {page!=='display'?<><div className="form-field"><span id="preference-name-label">你的称呼</span><input aria-labelledby="preference-name-label" aria-label="用户名称" maxLength={16} required value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/></div>
    <div className="form-field"><span id="daily-minutes-label">每天留给学习的时间</span><div className="input-unit"><input aria-labelledby="daily-minutes-label" aria-label="默认每日学习分钟" type="number" min={5} max={480} required value={draft.dailyMinutes} onChange={event=>setDraft({...draft,dailyMinutes:Number(event.target.value)})}/><span>分钟</span></div></div><div className="settings-info"><Check size={17}/><p>主页会显示你的每日目标；作为新计划的默认值，已确认的课程计划保留原设置。</p></div></>:<><fieldset className="theme-options"><legend>界面外观</legend><div className="theme-option-grid">{([{id:'light',name:'浅色',icon:Sun,description:'清爽的白色与克莱因蓝'},{id:'dark',name:'深色',icon:Moon,description:'沉静的墨蓝与柔和亮蓝'}] as const).map(({id,name,icon:Icon,description})=><label className={`theme-option ${draft.theme===id?'selected':''}`} key={id}><input type="radio" name="appearance" aria-label={`${name}外观`} checked={draft.theme===id} onChange={()=>setDraft({...draft,theme:id})}/><span className={`theme-preview ${id}`} aria-hidden="true"><span className="preview-rail"><i/><i/><i/></span><span className="preview-main"><span className="preview-top"><i/><i/></span><span className="preview-body"><i/><span><i/><i/></span></span></span></span><span className="theme-option-caption"><Icon size={16}/><strong>{name}</strong>{draft.theme===id&&<Check size={15}/>}</span><small>{description}</small></label>)}</div></fieldset></>}
    {initial.revision>draft.revision&&!error&&<p role="status">偏好已被另一页面修改。未保存输入与原修订号已保留。</p>}
    {(error||initial.revision>draft.revision)&&<p role={error?'alert':'status'}>{error}<button type="button" disabled={busy} onClick={async()=>{try{const latest=await workbenchRpc<UiPreferences>('uiPreferences');setDraft(latest);setBaseline(latest);setError('');}catch(error){setError(error instanceof Error?error.message:'加载失败');}}}>加载最新设置</button></p>}
    </div><footer className="settings-page-footer"><div><button type="button" className="button" onClick={onClose}>关闭</button><button className="button primary" disabled={busy}>{busy?'正在保存…':page==='display'?'保存外观':page==='profile'?'保存资料':'保存偏好'}</button></div></footer>
  </form>;
}
