import { afterEach, describe, expect, it } from 'vitest'
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { randomUUID } from 'node:crypto'
import { join, resolve } from 'node:path'
import { SylloraProjects } from '../src/syllora-projects.ts'
import type { ResolvedChatConfig } from '../src/config.ts'
import type { StructuredCallClient } from '@syllora/course-builder'
const roots:string[]=[]
afterEach(async()=>{for(const root of roots.splice(0))await rm(root,{recursive:true,force:true})})
const config:ResolvedChatConfig={providerId:'fixture',model:'fixture',baseUrl:'http://localhost:9999/v1',apiKey:'test-only',apiKeyEnv:null,temperature:0,maxConcurrency:1,digest:false,defaultMode:'quick'}
async function setup() {
  const temp=resolve('../tmp/ui-backend-integration-2026-10-02/unit');await mkdir(temp,{recursive:true});const root=await mkdtemp(join(temp,'case-'));roots.push(root)
  const folder=join(root,'course');await mkdir(folder);await writeFile(join(folder,'notes.md'),'# 单位矩阵\n\n单位矩阵的主对角线元素为一，其余元素为零。\n\n矩阵乘法需要左矩阵列数与右矩阵行数相等。')
  let calls=0,wait:Promise<void>|null=null
  const client:StructuredCallClient={async *stream(options){calls++;if(wait)await wait;const prompt=(options.messages.at(-1) as any).content[0].text,header=prompt.includes('初始化整理课程讲义')?'所选资料：\n':prompt.slice(prompt.lastIndexOf('\n所选资料（')).split('\n')[1]+'\n';const sources=JSON.parse(prompt.slice(prompt.lastIndexOf(header)+header.length));const source=sources.find((s:any)=>s.kind!=='heading')??sources[0];const output=prompt.includes('初始化整理课程讲义')?{chapter:'单位矩阵',intro:{text:'课程导读',sourceIds:sources.map((s:any)=>s.id)},concepts:[{name:'单位矩阵',text:'单位矩阵解释',sourceIds:[source.id],quote:source.text}],examples:[],connections:[],analogies:[]}:{text:'主对角线为一，其余元素为零。',sourceIds:[source.id],insufficient:false};yield {type:'text-delta',text:JSON.stringify(output)}}}
  const app=join(root,'app'),projects=new SylloraProjects(app,{config:async()=>config,client:()=>client});await projects.handle('preferences',{consent:true});const opened=await projects.handle('openCourse',{path:folder,icon:'math'}) as any
  const scan=await projects.handle('scan',{courseId:opened.id}) as any;const result=await projects.handle('initialize',{courseId:opened.id,requestId:randomUUID(),paths:scan.files.map((f:any)=>f.path),fingerprints:Object.fromEntries(scan.files.map((f:any)=>[f.path,f.fingerprint]))}) as any;await settle(projects,result.jobId)
  return {projects,id:opened.id,folder,app,calls:()=>calls,pause:(p:Promise<void>|null)=>{wait=p}}
}
async function settle(projects:SylloraProjects,id:string){for(let i=0;i<500;i++){const state=await projects.handle('state',{}) as any;const job=state.jobs.find((job:any)=>job.id===id);if(job&&job.state!=='running'){expect(job.state,job.message).toBe('succeeded');return {state,job}}await new Promise(resolve=>setTimeout(resolve,10))}throw new Error('job did not settle')}
async function context(s:Awaited<ReturnType<typeof setup>>){const state=await s.projects.handle('state',{}) as any,course=state.courses[0],material=course.materials[0];const document=await s.projects.handle('readingDocument',{courseId:s.id,materialId:material.id}) as any;const source=document.sources.find((source:any)=>source.kind!=='heading');return {document,reading:{materialId:material.id,revision:document.revision,sourceIds:[source.id],selection:source.text,mode:'explain'}}}
describe('production UI backend contracts',()=>{
  it('protects draft edits between pages and only clears the accepted prompt version',async()=>{const s=await setup();expect(await s.projects.handle('saveDraft',{courseId:s.id,baseVersion:0,prompt:'第一页问题',answers:[]})).toMatchObject({version:1});await expect(s.projects.handle('saveDraft',{courseId:s.id,baseVersion:0,prompt:'第二页输入',answers:[]})).rejects.toMatchObject({code:'VERSION_CONFLICT'});await s.projects.handle('saveDraft',{courseId:s.id,baseVersion:1,prompt:'更新的问题',answers:[]});const job=await s.projects.handle('generate',{courseId:s.id,kind:'answer',prompt:'第一页问题',requestId:randomUUID()}) as any;await settle(s.projects,job.jobId);expect((await s.projects.handle('state',{}) as any).courses[0].drafts).toMatchObject({prompt:'更新的问题',version:2})})
  it('removes persisted reading selections and results after their source is deleted',async()=>{const s=await setup(),{reading}=await context(s);const job=await s.projects.handle('generate',{courseId:s.id,kind:'answer',reading,requestId:randomUUID()}) as any;await settle(s.projects,job.jobId);await s.projects.handle('deleteMaterial',{courseId:s.id,materialId:reading.materialId,confirmed:true});const state=await s.projects.handle('state',{}) as any;expect(state.courses[0].messages.every((message:any)=>!message.reading&&message.sourceIds.length===0&&!message.text.includes(reading.selection))).toBe(true);expect(state.activity).toHaveLength(1)})
  it('persists shared preferences and rejects stale edits without changing consent',async()=>{const s=await setup();const first=await s.projects.handle('uiPreferences',{}) as any;expect(first.revision).toBe(0);await s.projects.handle('uiPreferences',{name:'同学',theme:'dark',dailyMinutes:50,baseVersion:0});await expect(s.projects.handle('uiPreferences',{name:'旧页',theme:'light',dailyMinutes:40,baseVersion:0})).rejects.toMatchObject({code:'VERSION_CONFLICT'});const restart=new SylloraProjects(s.app);expect(await restart.handle('uiPreferences',{})).toMatchObject({name:'同学',theme:'dark',dailyMinutes:50,revision:1});expect((await restart.handle('state',{}) as any).settings.consent).toBe(true)})
  it('requires a base version for preferences writes and serializes simultaneous saves',async()=>{const s=await setup();await expect(s.projects.handle('uiPreferences',{theme:'dark'})).rejects.toThrow();const results=await Promise.allSettled([s.projects.handle('uiPreferences',{name:'一',theme:'dark',dailyMinutes:50,baseVersion:0}),s.projects.handle('uiPreferences',{name:'二',theme:'light',dailyMinutes:40,baseVersion:0})]);expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1)})
  it('preserves course icons through reopening and rename',async()=>{const s=await setup();await s.projects.handle('rename',{courseId:s.id,name:'数学'});await s.projects.handle('openCourse',{path:s.folder});expect((await s.projects.handle('state',{}) as any).courses[0]).toMatchObject({name:'数学',icon:'math'});await s.projects.handle('archive',{courseId:s.id,archived:true});await s.projects.handle('openCourse',{path:s.folder,icon:'language'});expect((await s.projects.handle('state',{}) as any).courses[0]).toMatchObject({archived:true,icon:'language'});await expect(s.projects.handle('coursePresentation',{courseId:s.id,icon:'unknown'})).rejects.toThrow()})
  it('returns published sources with anchors and rejects cross-course material IDs',async()=>{const s=await setup();const c=await context(s);expect(c.document.source).toBe('published');expect(c.document.sources[0].anchor).toBeTruthy();await expect(s.projects.handle('readingDocument',{courseId:s.id,materialId:randomUUID()})).rejects.toMatchObject({code:'NOT_FOUND'})})
  it('generates reading answers through real jobs, links the result, and deduplicates activity',async()=>{const s=await setup();const {reading}=await context(s),requestId=randomUUID();const first=await s.projects.handle('generate',{courseId:s.id,requestId,kind:'answer',reading}) as any;await s.projects.handle('generate',{courseId:s.id,requestId,kind:'answer',reading});const result=await settle(s.projects,first.jobId);expect(result.state.courses[0].messages.find((m:any)=>m.id===result.job.resultMessageId)).toMatchObject({reading:{mode:'explain'}});expect(result.state.activity).toHaveLength(1);expect(result.state.activity[0]).toMatchObject({kind:'reading',minutes:0});expect(s.calls()).toBe(2);expect((await new SylloraProjects(s.app).handle('activity',{}) as any).activity).toHaveLength(1)})
  it('rejects forged selections and stale revisions before calling the model',async()=>{const s=await setup(),{reading}=await context(s),before=s.calls();await expect(s.projects.handle('generate',{courseId:s.id,requestId:randomUUID(),kind:'answer',reading:{...reading,selection:'凭空编造'}})).rejects.toMatchObject({code:'INVALID_SELECTION'});await expect(s.projects.handle('generate',{courseId:s.id,requestId:randomUUID(),kind:'answer',reading:{...reading,revision:randomUUID()}})).rejects.toMatchObject({code:'VERSION_CONFLICT'});expect(s.calls()).toBe(before)})
  it('allows reading without a consent toggle but cancels a late result on source deletion',async()=>{const s=await setup(),{reading}=await context(s);await s.projects.handle('preferences',{consent:false});expect((await s.projects.handle('state',{}) as any).settings.consent).toBe(true);let release!:()=>void;s.pause(new Promise(resolve=>{release=resolve}));const result=await s.projects.handle('generate',{courseId:s.id,requestId:randomUUID(),kind:'answer',reading}) as any;const deletion=s.projects.handle('deleteMaterial',{courseId:s.id,materialId:reading.materialId,confirmed:true});release();await deletion;const state=await s.projects.handle('state',{}) as any;expect(state.jobs.find((job:any)=>job.id===result.jobId).state).not.toBe('running');expect(state.courses[0].messages.filter((m:any)=>m.role==='assistant')).toHaveLength(0);expect(state.activity).toHaveLength(0);expect(await readFile(join(s.folder,'notes.md'),'utf8')).toContain('单位矩阵')})
})


describe('planning configuration persistence',()=>{
  it('persists selections and estimates independently of confirmed plans, rejecting stale pages',async()=>{
    const s=await setup();const original=(await s.projects.handle('state',{}) as any).courses[0];const pointId=original.points[0].id;
    expect(await s.projects.handle('planningDraft',{courseId:s.id,baseVersion:0,scope:[pointId],estimates:{[pointId]:35}})).toMatchObject({revision:1});
    const restart=new SylloraProjects(s.app);const restored=(await restart.handle('state',{}) as any).courses[0];
    expect(restored.planningDraft).toEqual({revision:1,scope:[pointId],estimates:{[pointId]:35}});
    expect(restored.scope).toEqual(original.scope);expect(restored.plan).toEqual(original.plan);
    await expect(s.projects.handle('planningDraft',{courseId:s.id,baseVersion:0,scope:[],estimates:{}})).rejects.toMatchObject({code:'VERSION_CONFLICT'});
    await expect(s.projects.handle('planningDraft',{courseId:s.id,baseVersion:1,scope:[randomUUID()],estimates:{}})).rejects.toThrow();
    await s.projects.handle('planningDraft',{courseId:s.id,baseVersion:1,scope:[],estimates:{}});
    expect((await s.projects.handle('state',{}) as any).courses[0].planningDraft.scope).toEqual([]);
  });
});
